config/routes.rb
Shopper::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  devise_for :users

  namespace :cart do 
    resources :users do 
      resources :addresses, only: [:index]
    end
  end
  
  resources :categories, only: [:index] do
    resources :products, only: [:index, :show]
  end
  
  resources :products do 
    resources :items, only: [:create]
  end
  
  resources :orders do 
    get ":id/status/:status", action: :show, as: :status, on: :collection
  end
  
  resources :carts do
    resources :addresses, only: [:new, :create]
  end
  
  resources :items
  resources :addresses
  resources :users do
    resources :orders
    resources :addresses
  end
  
  resources :guests, only: [:new, :create, :update]
  
  root to: 'home#index'
end

app/models/concerns/order/stateful.rb
class Order
  module Stateful
    extend ActiveSupport::Concern

    included do 
      scope :open_orders, -> { with_state(:cart) }

      state_machine initial: :cart do
        before_transition from: :cart,      to: :purchased, do: :validates_cart
        before_transition from: :cart,      to: :purchased, do: :validates_assign_email
        after_transition  from: :cart,      to: :purchased, do: :set_default_address
        after_transition  from: :cart,      to: :purchased, do: :consolidate_stock
        after_transition  from: :cart,      to: :purchased, do: :send_mail
        after_transition  from: :purchased, to: :canceled,  do: :return_stock
        after_transition  from: :purchased, to: :canceled,  do: :send_mail
        after_transition  from: :purchased, to: :shipped,   do: :send_mail

        event :purchase do
          transition from: :cart, to: :purchased
        end

        event :cancel do
          transition from: :purchased, to: :canceled
        end

        event :ship do
          transition from: :purchased, to: :shipped
        end
      end
    end

    def validates_cart
      address_id.present? and items.present?
    end

    def validates_assign_email
      user = address.user
      @user_exists = user_exists

      if @user_exists and @user_exists.member?
        errors.add(:guest_email, "Please sign in. This email had already been member.") 
      elsif not @user_exists and user.guest?
        errors.add(:guest_email, "Please enter email address.") if guest_email.blank?
        user.update_attributes(email: guest_email)
      end
    end

    def set_default_address
      user = address.user
      
      if @user_exists and @user_exists.guest?
        user.move_to(@user_exists)
        @user_exists.set_default_to(address)
        user = @user_exists
      elsif user.guest? or user.member?
        user.set_default_to(address)
      end
    end

    def consolidate_stock
      items.each { |item| item.consolidate_stock }
      calculate_balance
    end

    def return_stock
      items.each { |item| item.return_stock }
    end

    def send_mail
      case state
        when 'purchased' then OrderMailer.delay.purchased_state(self)
        when 'canceled'  then OrderMailer.delay.canceled_state(self)
        when 'shipped'   then OrderMailer.delay.shipped_state(self)
      end
    end

    private
    def user_exists
      @user_exists ||= User.find_by_email(guest_email)
    end
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  include Order::Stateful

  belongs_to :address
  has_many   :items,    order: 'created_at ASC'
  has_many   :products, through: :items

  attr_accessible :state, :token, :address_id, :address_attributes, :items_attributes, :state_event, :guest_email
  attr_accessor :guest_email

  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :items

  scope :only_completed, -> { where("state != ?", 'cart') }
  scope :only_cart,      -> { with_state(:cart) }
  scope :only_shipping,  -> { with_state(:shipped) }
  scope :only_cancel,    -> { with_state(:canceled) }

  delegate :email, to: :address

  alias_method :order_email, :email

  def get_balance
    total + ((not address or address.new_record?) ? 0 : address.rate).to_f
  end

  def self.cart_by token
    Order.where(token: token, state: 'cart').includes(items: [:product]).first
  end

  def calculate_items
    self.items_count = items.sum(&:quantity)
    self.total = items.sum(&:sub_total)
    self.save
  end

  def calculate_balance
    self.balance = get_balance
    self.save
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = current_user.orders.includes(address: [:country]).order('created_at DESC')
  end

  def show
    @order = get_order

    if @order
      get_guest if params[:status] and @order.state == params[:status]

      respond_to do |format|
        format.html
        format.js
        format.pdf do
          pdf = OrderPdf.new(@order, view_context)
          send_data pdf.render, filename: "order_#{@order.id}",
                                type: "application/pdf",
                                disposition: "inline"
        end
      end
    else
      redirect_to root_path, flash: { error: "Order is Unavailable." }
    end
  end

private
  def get_guest
    @guest = Guest.find_by_email(session[:guest_email])
    session.delete(:guest_email) unless @guest
  end

  def get_order
    if session[:guest_email]
      Order.where(id: params[:id]).first
    else
      current_user.orders.where(id: params[:id]).includes(items: [:product]).first
    end
  end
end

app/views/orders/status/_purchased.html.erb
<div class='container'>
  <div class='row'>
    <div class='span8 offset2'>
      <div class='well well-elderflower no-actions'>
        <%= content_tag :fieldset, class: 'order-invoice' do %>
          <span class='order'>Invoice No. #<%= @order.id %></span>
          <span class='pull-right'>
            <%= link_to order_path(@order, format: "pdf"), class: 'btn' do %>
              <i class='icon-print'></i> Print Invoice
            <% end %>
          </span>
        <% end %>
      </div>
      <div class='well well-elderflower no-actions'>
        <%= content_tag :fieldset do %>
          <p class='lead'>Thank you for your purchase, keep enjoy shopping! :)</p>
          <p>I hope you enjoy your Shopper products.</p>
          <p>Your transaction has been completed, and a receipt for your purchase has been emailed to you.</p>
          <p>If you have any questions about your order, or comments about your shopping experience, please contact our and let our know.</p>
          <br>
          <div class='pull-right'>
            <a href='/' class='btn'>Continue Shopping</a>
            <% if current_user and current_user.member? %><a href='<%= user_orders_path(current_user) %>' class='btn btn-success'>Go to Orders History</a><% end %>
          </div>
        <% end %>
      </div>
      <% if @guest.present? and @guest.guest? %>
        <%= render 'orders/status/purchased_sign_up' %>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/status/_purchased_sign_up.html.erb
<%= form_for @guest, as: :guest, url: guest_path(@guest), html: { class: 'form-horizontal well well-elderflower' } do |f| %>
  <%= content_tag :fieldset do %>
    <legend>Easy Access</legend>
    <div class='control-group'>
      <%= f.label :password, class: 'control-label' %>
      <div class='controls'>
        <%= f.password_field :password, placeholder: "Password" %>
        <span class="help-inline"><small>minimum is 6 characters</small></span>
      </div>
    </div>
    <div class='control-group'>
      <%= f.label :password_confirmation, 'Retype', class: 'control-label' %>
      <div class='controls'>
        <%= f.password_field :password_confirmation, placeholder: "Password confirmation" %>
      </div>
    </div>
  <% end %>
  <div class='form-actions'>
    <%= f.submit 'Create Account', class: 'btn btn-success' %>
  </div>
<% end %>