config/routes.rb
Shopper::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  devise_for :users

  namespace :cart do 
    resources :users do 
      resources :addresses, only: [:index]
    end
  end
  
  resources :categories, only: [:index] do
    resources :products, only: [:index, :show]
  end
  
  resources :products do 
    resources :items, only: [:create]
  end
  
  resources :orders do 
    get ":id/status/:status", action: :show, as: :status, on: :collection
  end
  
  resources :carts do
    resources :addresses, only: [:new, :create]
  end
  
  resources :items
  resources :addresses
  resources :users do
    resources :orders
    resources :addresses
  end
  
  resources :guests, only: [:new, :create, :update]
  
  root to: 'home#index'
end

app/views/layouts/shared/_footer.html.erb
<footer>
  <div class='container'>
    <div class='row'>
      <div class='span12 copy-right'>
        <hr>
        <p>© 2012 Artellectual Co., Ltd</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/shared/_header.html.erb
<div class="navbar navbar-pastel navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to root_path, class: "brand" do %>Shopper<% end %>
      <%= render "layouts/shared/navigation" %>
    </div>
  </div>
</div>

app/views/layouts/shared/_navigation.html.erb
<ul class="nav pull-right">
  <%= render_menu_for("Home", root_path) %>
  <%= render_menu_for("Store", products_path, /products/) %>
  <%= render_cart_menu %>
  <%= render_user_menu %>
</ul>