config/routes.rb
Shopper::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  devise_for :users

  namespace :cart do 
    resources :users do 
      resources :addresses, only: [:index]
    end
  end
  
  resources :categories, only: [:index] do
    resources :products, only: [:index, :show]
  end
  
  resources :products do 
    resources :items, only: [:create]
  end
  
  resources :orders do 
    get ":id/status/:status", action: :show, as: :status, on: :collection
  end
  
  resources :carts do
    resources :addresses, only: [:new, :create]
  end
  
  resources :items
  resources :addresses
  resources :users do
    resources :orders
    resources :addresses
  end
  
  resources :guests, only: [:new, :create, :update]
  
  root to: 'home#index'
end

app/controllers/carts_controller.rb
class CartsController < OrdersController
  before_filter :check_items, only: [:edit]
  
  def show
    @cart = Order.where(id: params[:id]).includes(items: [:product]).first
  end

  def edit
    @cart = Order.where(id: params[:id]).includes(items: [:product]).first
    @cart.address = get_address || current_or_guest_user.default_address || Address.new
  end

  def update
    @cart = Order.find(params[:id])
    if @cart.update_attributes(params[:order])
      setup_guest(@cart) if params[:order][:guest_email]
    else
      render_box_error_for(@cart)
    end
  end

private
  def check_items
    if current_order.items_count.eql?(0)
      respond_to do |format|
        format.js { render js: "window.location = '/'" }
        format.html { 
          flash[:error] = "You should add product to cart before purchase."
          redirect_to root_path
        }
      end
    end
  end

  def setup_guest(cart)
    reset_session; cart.reload
    session[:guest_email] = cart.address.email
  end

  def get_address
    current_or_guest_user.addresses.where(id: @cart.address_id).first
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def check_out
    current_user ? edit_cart_path(current_order) : new_guest_path
  end
end

app/views/carts/purchase/_confirm.html.erb
<%= form_for cart, url: cart_path(cart), remote: true, html: {class: 'form-horizontal'} do |f| %>
  <div class='modal-header'>
    <button class='close' data-dismiss='modal' aria-hidden='true'>&times;</button>
    <h4>Place Order</h4>
  </div>
  <div class='modal-body'>
    <p>Shopper's shop will send purchase order's information in your email address (<%= current_user.email %>).</p>
    <%= f.hidden_field :address_id, value: cart.address_id %>
    <%= f.hidden_field :state_event, value: 'purchase' %>
  </div>
  <div class='modal-footer'>
    <button class='btn' data-dismiss='modal' aria-hidden='true'>Cancel</button>
    <%= f.submit "Confirm", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/carts/purchase/_confirm_guest.html.erb
<%= form_for cart, url: cart_path(cart), remote: true, html: {class: 'form-horizontal'} do |f| %>
  <div class='modal-header'>
    <button class='close' data-dismiss='modal' aria-hidden='true'>&times;</button>
    <h4>Place Order</h4>
  </div>
  <div class='modal-body'>
    <p>Shopper's shop will send purchase order's information in your email address.</p>
    <%= f.text_field :guest_email, autofocus: true, placeholder: "Your email address", class: 'span4' %>
    <%= f.hidden_field :address_id, value: cart.address_id %>
    <%= f.hidden_field :state_event, value: 'purchase' %>
  </div>
  <div class='modal-footer'>
    <button class='btn' data-dismiss='modal' aria-hidden='true'>Cancel</button>
    <%= f.submit "Confirm", class: 'btn btn-success' %>
  </div>
<% end %>